// <auto-generated />
namespace CMS.Infra.Data.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addcontentMapping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcontentMapping));
        
        string IMigrationMetadata.Id
        {
            get { return "201906241338181_add-contentMapping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
