// <auto-generated />
namespace CMS.Infra.Data.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatecategorymm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatecategorymm));
        
        string IMigrationMetadata.Id
        {
            get { return "201906171437312_update-categorymm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
