//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.StaticResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMS.StaticResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận xóa?.
        /// </summary>
        public static string MSG_CONFIRM_DELETE {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thành công.
        /// </summary>
        public static string MSG_TEXT_CREATE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_TEXT_CREATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một khi đã xóa, bạn không thể khôi phục lại.
        /// </summary>
        public static string MSG_TEXT_DELETE {
            get {
                return ResourceManager.GetString("MSG_TEXT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        public static string MSG_TEXT_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_TEXT_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi, vui lòng thử lại.
        /// </summary>
        public static string MSG_TEXT_ERROR_TRYAGAIN {
            get {
                return ResourceManager.GetString("MSG_TEXT_ERROR_TRYAGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công.
        /// </summary>
        public static string MSG_TEXT_UPDATE_SUCCESS {
            get {
                return ResourceManager.GetString("MSG_TEXT_UPDATE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác.
        /// </summary>
        public static string TEXT_ACTION {
            get {
                return ResourceManager.GetString("TEXT_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string TEXT_CLOSE {
            get {
                return ResourceManager.GetString("TEXT_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới.
        /// </summary>
        public static string TEXT_CREATE {
            get {
                return ResourceManager.GetString("TEXT_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string TEXT_DELETE {
            get {
                return ResourceManager.GetString("TEXT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền.
        /// </summary>
        public static string TEXT_ROLE {
            get {
                return ResourceManager.GetString("TEXT_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phân quyền.
        /// </summary>
        public static string TEXT_ROLENAME {
            get {
                return ResourceManager.GetString("TEXT_ROLENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string TEXT_UPDATE {
            get {
                return ResourceManager.GetString("TEXT_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật claims.
        /// </summary>
        public static string TEXT_UPDATE_ROLE_CLAIM {
            get {
                return ResourceManager.GetString("TEXT_UPDATE_ROLE_CLAIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật phân quyền menu.
        /// </summary>
        public static string TEXT_UPDATE_ROLE_MENU {
            get {
                return ResourceManager.GetString("TEXT_UPDATE_ROLE_MENU", resourceCulture);
            }
        }
    }
}
